<%@ Page language="VB" %>
<%@ Import Namespace="System.Net" %>
<%@ Import Namespace="System.IO" %>
<%@ Import Namespace="System.Text" %>
<%@ Import Namespace="System.Web" %>
<%@ Import Namespace="System.Web.Mail" %>
<%@ Import Namespace="System.Data" %>
<%@ Import Namespace="System.Data.SqlClient" %>
<%@ Import Namespace="System.Data.SqlTypes" %>
<%@ Import Namespace="System.Configuration" %>
<%@ Import Namespace="DotNetNuke" %>
<%@ Import Namespace="DotNetNuke.Common" %>
<%@ Import Namespace="DotnetNuke.Entities.Portals" %>
<%@ Import Namespace="DotNetNuke.jb_Uconversion" %>

<script runat="server">
    Private MyFileName As String = "jb_PaymentNotify.aspx"

    '============================================================================
    '1) Controls Declaration & DNN Variables
    '============================================================================
    '1.1) Control Declaration
    '1.2) DNN Page Variables
    Dim thisModule As Integer = -1
    Dim thisPortal As Integer
    Dim thisTab As Integer
    Dim thisUserID As Integer 'Not using at the moment
    Dim IPNWaitTime As Integer = 0
    Dim ShowIPNError As Boolean = False
    Dim Settings As Hashtable
    Dim qs As String = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Please contact admin.")
    Dim _portalSettings As PortalSettings = DotNetNuke.Entities.Portals.PortalController.GetCurrentPortalSettings

    '============================================================================
    '2) PayPal Variables
    '============================================================================
    'Declare our variables we will be receiving
    'We declare this part at the top because these variable will be use throughout several subs
    '2.1) Core variables
    Dim payment_status As String
    Dim payment_gross As String
    Dim mc_gross As String
    Dim mc_fee As String
    Dim txn_id As String 'A unique transaction ID generated by the PayPal system
    Dim item_number As String
    Dim payer_email As String
    Dim payer_id As String
    Dim receiver_email As String ' This is an email that you will receive the paymet, equivalent to "business"
    Dim item_name As String
    Dim quantity As String
    Dim num_cart_items As Integer

    '2.2) Additional pieces if information we might want to collect
    Dim invoice, pending_reason, _
    payment_date, payment_fee, txn_type, first_name, last_name, address_street, _
    address_city, address_state, address_zip, address_country, address_status, _
    payer_status, payment_type, notify_version, verify_sign, subscr_date, _
    period1, period2, period3, amount1, amount2, amount3, recurring, reattempt, _
    retry_at, recur_times, username, subscr_id As String
    Dim mc_shipping, mc_handling, mc_tax, shipping, tax As Decimal
    Dim custom As String


    '2.3) Security variable
    Dim boolDuplicateTxn_ID As Boolean = False 'Check to see if this is duplicate transaction
    Dim boolIsCorrectAmount As Boolean = False 'Check total amount paid to match total sale amount 

    '2.4) Object Variables used for recoding paypal transactions to our backend database 
    'xx_
    Dim objClassifieds As New jb_ClassifiedsDB
    '2008 
    Dim objSubscriptionPlan As New jb_SubscriptionPlan
    Dim objOrders As New jb_Orders
    Dim objOrderDetail As New jb_OrderDetail
    Dim strTemporaryPassword As String = ""
    Dim AssignedOrderID As Integer


    '2.5) Other Variables
    Dim thisCategoryID As Integer
    Dim thisAssignedItemID As Integer
    Dim strPostMode As String ' "live" or "sandbox"
    Dim strAdminEmail As String
    Dim strPayPalReceiverEmail As String
    Dim strPayPalMsgSuccess As String
    Dim strPayPalMsgError As String
    Dim thisPaypalIPNEnable As String
    Dim thisPayPalListingFeeMethod As String
    Dim thisPayPalOperationMode As String
    Dim thisPayPalFlatFeeAmount As Decimal
    Dim thisPayPalExpirationDays_FeeBased As Integer
    Dim thisExpirationDays As Integer
    Dim thisRequireAuthorization As String = "1"
    Dim strIPNMessages As String = ""   'This is a message then will be appended to the payment notification email

    Protected WithEvents hplContactSupportDesk As System.Web.UI.WebControls.HyperLink

#Region " Web Form Designer Generated Code "

    'This call is required by the Web Form Designer.
    <System.Diagnostics.DebuggerStepThrough()> Private Sub InitializeComponent()

    End Sub

    'NOTE: The following placeholder declaration is required by the Web Form Designer.
    'Do not delete or move it.
    Private designerPlaceholderDeclaration As System.Object

    Private Sub Page_Init(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Init
        'CODEGEN: This method call is required by the Web Form Designer
        'Do not modify it using the code editor.
        InitializeComponent()
        StyleSheet.Attributes.Add("href", Page.ResolveUrl("~/DesktopModules/PA_JobBoard/module.css"))
    End Sub

#End Region

    Private Sub Page_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        'LocalResourceFile = DotNetNuke.Services.Localization.Localization.GetResourceFile(Me, MyFileName)
        '******************************************************
        'A) SET Page Control properties (optional)
        '******************************************************


        '******************************************************
        'B) Process PayPal Data
        '******************************************************
        Try 'T1
            '==========================================================================================================
            'SECTION 1: Retrive Posted Variables/Verify Duplicate Transactions
            '==========================================================================================================
            'At the time the payment is made, PayPal will post a notification to this page 
            'on your server. All the following pieces of information will be collected and assigned to local variables for later use
            'Note: all local variables for PalPal will be lowercase_lowercase

            RetrivePostedVariables() 'all posted values will be kept in the page scope local variables
            Init_Module_Settings()
            'If IPNWaitTime > 0 Then
            '    System.Threading.Thread.Sleep(IPNWaitTime * 1000)
            'End If
            SetPageControlProperties()
            '2008
            VerifyDuplicateTransaction()

            '======================================================================================
            'SECTION 2: Post formPostData to PayPal to Server and see if the response is "VERIFIED"
            '======================================================================================
            'On receiving the notification in section 1, this section will send information (formPostData)
            'back to a secure PayPal URL. PayPal will authenticate the transaction and send to this page agian
            'The resonse will be either "VERIFIED" or "INVALID"
            'This Post-Back of the IPN data to PayPal is required to prevent "Spoofing" so you can be sure that
            'the IPN came from PayPal.
            'Note: Spoofing is the way that someone is pretending to someone else. In this case someone might try
            'to pretend to be PayPal

            If VerifyIPN(strPostMode) Then 'The response is "VERIFIED"
                '======================================================
                'SECTION 3: response is "VERIFIED"
                '======================================================
                '3.1) Check payment_status (Completed,Pending,Failed,Denied)
                '3.2) Check receiver_email (from IPN) = strPayPalReceiverEmail (From module settings)
                '3.3) Check txn_type  (web_accept,cart,send_money) 
                '       Verify payment amount boolIsCorrectAmount(True / False) by checking (mc_gross = decDatabase_PriceCheckAmount)
                '       Populate strDownloadItems for download items 
                '3.4) IF 1) Completed, 2) matched and 3) not duplicate THEN proceed otherwise show error text
                '3.5) What we will get by the end is an appropriate QueryString [qs = "&msgcode=pps"] that will be passed to the MessageBox.ascx 

                '===========================
                '3.1) Check payment_status
                '===========================

                Select Case (payment_status) 'SC2: payment_status (Completed,Pending,Failed,Denied)
                    Case "Completed" 'The payment has been completed and the funds are successfully in your account balance

                        '=====================================================================================
                        '3.2) Check receiver_email (from IPN) = strPayPalReceiverEmail (From module settings)
                        '=====================================================================================
                        If LCase(receiver_email) = LCase(strPayPalReceiverEmail) Then
                            '=======================================================
                            '3.3) Check txn_type  (web_accept,cart,send_money,etc) 
                            '=======================================================                               

                            '=======================================================
                            'A) ADD Order to jb_Orders table
                            '=======================================================
                            '2008
                            Dim strCompleteStatus As String = "IPNCompleted"
                            Dim strReference As String = Me.thisPayPalListingFeeMethod
                            If Me.thisCategoryID = -8 Then 'Renewal for existing ItemID
                                strCompleteStatus = "IPNRenewal"
                                strReference = "RenewalFee"
                            End If
                            If boolDuplicateTxn_ID = False Then
                                strTemporaryPassword = DotNetNuke.jb_Utility.CreateTemporaryPassword(8)
                                'Insert to Orders table and get the auto generated OrderID (will be used again to insert OrderDetail)                                  
                                AssignedOrderID = objOrders.jb_OrdersAdd(Me.thisPortal, Me.thisModule, Me.thisUserID, strCompleteStatus, NullString, strReference, NullString, NullString, Me.thisUserID, NullString, NullDecimal, NullDecimal, NullDecimal, NullDecimal, "", _
                                                True, Me.payer_email, Me.payer_id, Me.payment_status, Me.txn_id, Me.txn_type, Me.mc_gross, Me.mc_fee, Me.payment_date, _
                                                 invoice, custom, pending_reason, payment_type, num_cart_items, mc_shipping, mc_handling, mc_tax, shipping, tax, first_name, last_name, address_street, address_city, address_state, address_zip, address_country, address_status, strTemporaryPassword)

                            End If

                            Select Case (txn_type) 'SC3.1: txn_type (web_accept,cart,send_money,subscr_signup,subscr_cancel,subscr_failed,subscr_payment)
                                Case "web_accept"

                                    Dim decPayment As Decimal = 0
                                    If InStr(ConvertString(Me.thisPayPalListingFeeMethod), "PerCategoryFee") > 0 Then
                                        decPayment = objClassifieds.jb_ClassifiedsCheckCategoryPayment(Me.thisCategoryID)
                                    ElseIf InStr(ConvertString(Me.thisPayPalListingFeeMethod), "FlatFee") > 0 Then
                                        decPayment = Double.Parse(Me.thisPayPalFlatFeeAmount).ToString().Replace(",", ".")
                                    Else 'SubscriptionFee use item_number as PlanID
                                        decPayment = Double.Parse(objSubscriptionPlan.jb_SubscriptionPlan_Jedi_GetSinglePlanFee(item_number)).ToString().Replace(",", ".")
                                    End If
                                    If Me.thisCategoryID = -8 Then 'Renewal for existing ItemID
                                        decPayment = Double.Parse(objSubscriptionPlan.jb_SubscriptionPlan_Jedi_GetSinglePlanFee(item_number)).ToString().Replace(",", ".")
                                    End If
                                    '=======================================================
                                    'B) ADD OrderDetails to jb_OrderDetail table
                                    '=======================================================
                                    If boolDuplicateTxn_ID = False Then
                                        objOrderDetail.jb_OrderDetailAdd(AssignedOrderID, Me.item_number, Me.item_name, Me.quantity, decPayment, decPayment * 1, True, Me.txn_id,Me.thisAssignedItemID)
                                    End If

                                    '============================================================
                                    '3.3) Verify payment amount 
                                    '============================================================
                                    PayPal_PriceCheck(decPayment)
                                    strIPNMessages = strIPNMessages & GetInit_strIPNMessages() & vbCrLf
                                    strIPNMessages = strIPNMessages & "Item/Plan Name: " & Me.item_name & vbCrLf
                                    strIPNMessages = strIPNMessages & "Item/Plan Number: " & Me.item_number & vbCrLf
                                    '==============================================================
                                    'C) Update PriceCheck Status for the same record inserted in A)
                                    '==============================================================
                                    objOrders.jb_OrdersUpdate_pp_PriceCheck(decPayment * 1, Me.tax, Me.shipping, decPayment * 1, boolIsCorrectAmount, Me.txn_id)

                                Case "cart"
                                    strIPNMessages = strIPNMessages & GetInit_strIPNMessages() & vbCrLf
                                Case "send_money"       'This payment was sent by your customer from the PayPal website, imports the "Send Money" tab
                                    strIPNMessages = strIPNMessages & GetInit_strIPNMessages() & vbCrLf
                                Case "subscr_signup"    'This IPN is for a subscription sign-up
                                    strIPNMessages = strIPNMessages & GetInit_strIPNMessages() & vbCrLf
                                Case "subscr_cancel"    'This IPN is for a subscription cancellation
                                    strIPNMessages = strIPNMessages & GetInit_strIPNMessages() & vbCrLf
                                Case "subscr_failed"    'This IPN is for a subscription payment failure
                                    strIPNMessages = strIPNMessages & GetInit_strIPNMessages() & vbCrLf
                                Case "subscr_payment"   'This IPN is for a subscription payment
                                    strIPNMessages = strIPNMessages & GetInit_strIPNMessages() & vbCrLf
                                Case "subscr_eot"       'This IPN is for a subscription's end of term
                                    strIPNMessages = strIPNMessages & GetInit_strIPNMessages() & vbCrLf
                            End Select


                            'after checking the transaction type
                            '1)strResponse =  "VERIFIED"
                            '2)payment_status =  "Completed" 
                            '3)receiver_email = strPayPalReceiverEmail
                            '4)boolIsCorrectAmount = True

                            '==============================================================================
                            '3.4) If 1) 2) 3) 4) are OK then proceed
                            '==============================================================================

                            If boolIsCorrectAmount = True Then
                                '***************************************
                                '  $Final Destination B4 Redirection$
                                '***************************************
                                'Change Business Rules based on type of products/services you provide 
                                '1) Tangible Goods
                                '2) Digital Goods
                                '3) Listing Service
                                'Check if Authorization is require. If not update the Active flag for this listing to true
                                Session("jb_ListingTxnID") = Me.txn_id

                                'Set Redirection qs QueryString 
                                '==============================================================================
                                '3.5) Set an appropriate qs to be passed to MessageBox.ascx
                                '==============================================================================
                                If Me.thisRequireAuthorization = "0" Then
                                    'The post item doesn't need to be approved by an admin by checking the chkAuth
                                    'Automatically authorized listing after payment is verified
                                    objClassifieds.jb_UpdateClassifiedsAuthed(Me.item_number, True)
                                    qs = "&msgcode=pps&msgcontent=" & HttpUtility.HtmlEncode("Your listing has been authorized.")
                                Else
                                    qs = "&msgcode=pps&msgcontent=" & HttpUtility.HtmlEncode("Your listing has been submitted for authorization.")
                                End If

                                'strPayPalMsgSuccess is the message in the module setting for success payment
                                strIPNMessages = strIPNMessages & strPayPalMsgSuccess & vbCrLf
                            Else
                                Session("jb_ListingTxnID") = Nothing
                                qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Payment Amount does not match.")
                                strIPNMessages = strIPNMessages & "Payment Amount does not match." & vbCrLf
                            End If 'boolIsCorrectAmount = True
                        Else 'If receiver_email = strPayPalReceiverEmail 
                            'The receiver_email does not match
                            'The buyer paid to someone else
                            qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Receiver Email does not match.")
                            strIPNMessages = strIPNMessages & "Receiver Email does not match." & vbCrLf
                        End If 'If receiver_email = strPayPalReceiverEmail 
                        '---- Send Email -------1) Case "Completed"
                        SendNotifyEmail(strIPNMessages, True) 'This will send an email to both admin and buyers
                    Case "Pending" ' The payment is pending - see the "pending reason" variable below for more information. Note: You will receive another instant payment notification when the payment becomes "completed", "failed", or "denied"
                        Select Case (pending_reason) 'SC3.2: 
                            Case "echeck"       'The payment is pending because it was made by an eCheck, which has not yet cleared
                                qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("The payment is pending because it was made by an eCheck. PayPal usually takes 4 business days for this process.")
                            Case "intl"         'The payment is pending because you, the merchant, hold an international account and do not have a withdrawal mechanism. You must manually accept or deny this payment from your Account Overview
                                qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Your order is pending (" & pending_reason & "). Please contact Admin.")
                            Case "verify"       'The payment is pending because you, the merchant, are not yet verified. You must verify your account before you can accept this payment
                                qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Your order is pending (" & pending_reason & "). Please contact Admin.")
                            Case "address"      'The payment is pending because your customer did not include a confirmed shipping address and you, the merchant, have your Payment Receiving Preferences set such that you want to manually accept or deny each of these payments. To change your preference, go to the "Preferences" section of your "Profile"
                                qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Your order is pending (" & pending_reason & "). Please contact Admin.")
                            Case "upgrade"      'The payment is pending because it was made via credit card and you, the merchant, must upgrade your account to Business or Premier status in order to receive the funds
                                qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Your order is pending (" & pending_reason & "). Please contact Admin.")
                            Case "unilateral"   'The payment is pending because it was made to an email address that is not yet registered or confirmed
                                qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Your order is pending (" & pending_reason & "). Please contact Admin.")
                            Case "other"        'The payment is pending for an "other" reason. For more information, contact customer service
                                qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Your order is pending (" & pending_reason & "). Please contact Admin.")
                        End Select
                        '---- Send Email -------2) Case "Pending"
                        SendNotifyEmail("PayPal Payment Notification: Order is waiting to be processed.", True)
                    Case "Failed"
                        qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Payment Failed.")
                        '---- Send Email -------3) Case "Failed"
                        SendNotifyEmail("PayPal Payment Notification: Payment Failed.", True)
                    Case "Denied"
                        qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Payment Denied.")
                        '---- Send Email -------4) Case "Denied"
                        SendNotifyEmail("PayPal Payment Notification: Payment Denied.", True)
                End Select 'Select Case (payment_status)

            Else 'The response is "INVALID"
                qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Response is NOT VERIFIED.")
                '---- Send Email ------
                'Send an email to admin

                SendNotifyEmail("PayPal Payment Notification: Response is NOT VERIFIED.", True)

            End If 'If VerifyIPN(strPostMode) Then 
        Catch ex As Exception 'T1
            If Session("jb_ListingTxnID") Is Nothing Then
                If payment_status = "Completed" Then
                    qs = "&msgcode=pps&msgcontent=" & HttpUtility.HtmlEncode("Transaction Completed")
                Else
                    If ShowIPNError = True Then
                        qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode(ex.Message.ToString())
                    Else
                        qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode("Error. Please contact Portal Admin for more information.")
                    End If
                End If
            Else
                qs = "&msgcode=pps&msgcontent=" & HttpUtility.HtmlEncode("Transaction Completed")
            End If
        Finally
            '''Response.Write(VerifyIPN(strPostMode))
            '''Response.Write("<BR>")
            '''Response.Write(strIPNMessages.ToString())
            '''Response.Write("<BR>")
            '''Response.Write(qs.ToString())

            '******************************************************
            'C) Handle Redirection 
            '******************************************************
            If Me.thisCategoryID = -8 Then
                qs = qs & "&RenewalItemID=" & Me.thisAssignedItemID
            End If
            Response.Redirect(jb_Utility.BuildDesktopLink(Me.thisTab, "msg", qs), False)
            '2008
            'If subscription then redirect to my subsription page
        End Try 'T1
     

    End Sub

    Public Sub SendNotifyEmail(ByVal strIPNMessages As String, Optional ByVal SendToUser As Boolean = False, Optional ByVal PopulateSessionOnly As Boolean = False)

        If boolDuplicateTxn_ID = True Then 'This txn_id is already in the database. DO NOT send an email again
            Exit Sub
        End If

        Dim strEmail_Subject As String
        Dim strEmail_Subject_Admin As String
        Dim sEmail_Body_Admin As String
        Dim sEmail_Body_User As String
        Dim sEmail_ListingInfo As String = ""
        Dim strListingURL As String
        '******************************************************
        'Email Subject 
        '******************************************************
        strEmail_Subject = _portalSettings.PortalName & ": " & DotNetNuke.jb_Uglobal.glbProductName & " -- Purchase/Listing Information"
        strEmail_Subject_Admin = _portalSettings.PortalName & ": " & DotNetNuke.jb_Uglobal.glbProductName & " -- Admin Notification # " & txn_id

        '******************************************************
        'Listing Information 
        '******************************************************
        strListingURL = "http://" & GetDomainName(System.Web.HttpContext.Current.Request) & "/" & glbDefaultPage & "?tabid=" & Me.thisTab
        If Me.thisCategoryID = -8 Then 'Renewal for existing ItemID
            strListingURL = strListingURL & "&lfm=" & Me.thisPayPalListingFeeMethod & "&uc=info&ItemID=" & Me.thisAssignedItemID & "&ref=" & Me.strTemporaryPassword & "&txn_id=" & txn_id
        Else
            Select Case Me.thisPayPalListingFeeMethod
                Case "FlatFee", "PerCategoryFee"
                    strListingURL = strListingURL & "&lfm=" & Me.thisPayPalListingFeeMethod & "&uc=info&ItemID=" & Me.thisAssignedItemID & "&ref=" & Me.strTemporaryPassword & "&txn_id=" & txn_id
                Case Else 'My Subscription page
                    strListingURL = strListingURL & "&lfm=" & Me.thisPayPalListingFeeMethod & "&uc=sc&ref=" & Me.strTemporaryPassword & "&txn_id=" & txn_id
            End Select
        End If
        sEmail_ListingInfo = sEmail_ListingInfo _
         & "LISTING INFORMATION" & vbCrLf _
         & "URL:  " & strListingURL & vbCrLf & vbCrLf
        '*****************************************************************************
        'Email Body: Listing Info + Transaction Info + User Address 
        '****************************************************************************
        sEmail_Body_Admin = "" _
                     & "Item/Plan Name:  " & item_name & vbCrLf _
                     & "Item/Plan Number:" & item_number & vbCrLf & vbCrLf _
                     & sEmail_ListingInfo _
                     & "PURCHASE INFORMATION" & vbCrLf _
                     & "Transaction ID:  " & txn_id & vbCrLf _
                     & "Transaction Type:" & txn_type & vbCrLf _
                     & "Payment Type:    " & payment_type & vbCrLf _
                     & "Payment Status:  " & payment_status & vbCrLf _
                     & IIf(ConvertString(pending_reason) <> "", "Pending Reason:  " & pending_reason & vbCrLf, "") _
                     & "Payment Date:    " & payment_date & vbCrLf _
                     & "Receiver Email:  " & receiver_email & vbCrLf _
                     & "Invoice:         " & invoice & vbCrLf _
                     & "MC Gross:        " & mc_gross & vbCrLf _
                     & "MC Shipping:     " & mc_shipping & vbCrLf _
                     & "MC Handling:     " & mc_handling & vbCrLf _
                     & "Shipping:        " & shipping & vbCrLf _
                     & "Total S & H:     " & (mc_shipping + mc_handling + shipping).ToString() & vbCrLf _
                     & "Tax:             " & tax & vbCrLf _
                     & "Payment Fee:     " & payment_fee & vbCrLf _
                     & "Payer Email:     " & payer_email & vbCrLf _
                     & "First Name:      " & first_name & vbCrLf _
                     & "Last Name:       " & last_name & vbCrLf _
                     & "Street Address:  " & address_street & vbCrLf _
                     & "City:            " & address_city & vbCrLf _
                     & "State:           " & address_state & vbCrLf _
                     & "Zip Code:        " & address_zip & vbCrLf _
                     & "Country:         " & address_country & vbCrLf _
                     & "Address Status:  " & address_status & vbCrLf _
                     & "Payer Status:    " & payer_status & vbCrLf _
                     & "Verify Sign:     " & verify_sign & vbCrLf _
                     & "Notify Version:  " & notify_version & vbCrLf

        sEmail_Body_User = strIPNMessages & vbCrLf _
                   & sEmail_ListingInfo _
                   & "TRANSACTION INFORMATION" & vbCrLf _
                   & "Transaction ID:  " & txn_id & vbCrLf _
                   & "Transaction Type:" & txn_type & vbCrLf _
                   & "Payment Type:    " & payment_type & vbCrLf _
                   & "Payment Status:  " & payment_status & vbCrLf _
                   & IIf(ConvertString(pending_reason) <> "", "Pending Reason:  " & pending_reason & vbCrLf, "") _
                   & "Payment Date:    " & payment_date & vbCrLf _
                   & "Receiver Email:  " & receiver_email & vbCrLf _
                   & "MC Gross:        " & mc_gross & vbCrLf _
                   & "S & H:           " & (mc_shipping + mc_handling + shipping).ToString() & vbCrLf _
                   & "Tax:             " & tax & vbCrLf _
                   & "Payer Email:     " & payer_email & vbCrLf _
                   & "Payer Status:    " & payer_status & vbCrLf _
                   & "Customer Name:   " & first_name & " " & last_name & vbCrLf _
                   & "Street Address:  " & address_street & vbCrLf _
                   & "City:            " & address_city & vbCrLf _
                   & "State:           " & address_state & vbCrLf _
                   & "Zip Code:        " & address_zip & vbCrLf _
                   & "Country:         " & address_country & vbCrLf _
                   & "Address Status:  " & address_status & vbCrLf

        Session("jb_PurchaseInformation") = sEmail_Body_User.Replace(strListingURL, DotNetNuke.Common.Utilities.HtmlUtils.FormatWebsite(strListingURL))
        If PopulateSessionOnly = True Then
            Exit Sub
        End If
        'Only send notification for "Completed" payment
        If payment_status <> "Completed" Then
            Exit Sub
        End If

        Try
            'Send notification to Admin
            DotNetNuke.jb_UEmail.Jedi_SendNotification(payer_email, strAdminEmail, "", strEmail_Subject_Admin, sEmail_Body_Admin, "", "", "", "", "", "")
            If SendToUser = True Then
                'Send notification to the user (with the same information)
                DotNetNuke.jb_UEmail.Jedi_SendNotification(strAdminEmail, payer_email, "", strEmail_Subject, sEmail_Body_User, "", "", "", "", "", "")
            End If
        Catch ex As Exception
            lblMessage.Text = "Error:" & ex.Message.ToString & "<br>Please contact Portal Admin for more information."
        End Try
    End Sub
    Public Function GetInit_strIPNMessages() As String
        Return "*** Please print this page for future reference. ***"
    End Function
    Private Sub cmdReturnHome_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdReturnHome.Click
        Response.Redirect(NavigateURL(Me.thisTab), False)
    End Sub

    Public Sub Init_Module_Settings()

        Dim CustomValueArray() As String = DotNetNuke.jb_Upaypal.GetCustomValueArray(ConvertString(Request.Params("custom")))
        'ModuleID, CategoryID, AssignedItemID, UserID, ListingFeeMethod
        If Not ConvertString(CustomValueArray(0)) = "" Then
            Me.thisModule = ConvertInteger(CustomValueArray(0))
        Else
            Me.thisModule = Request.QueryString("mid")
        End If

        Me.thisCategoryID = ConvertInteger(CustomValueArray(1))
        Me.thisAssignedItemID = ConvertInteger(CustomValueArray(2))
        Me.thisUserID = ConvertInteger(CustomValueArray(3))
        If ConvertString(CustomValueArray(4)) <> "" Then
            thisPayPalListingFeeMethod = ConvertString(CustomValueArray(4))
        Else
            thisPayPalListingFeeMethod = ConvertString(Settings("PayPalListingFeeMethod"))
        End If

        Settings = _portalSettings.GetModuleSettings(thisModule)
        thisTab = ConvertInteger(Settings("TabId"))
        thisPortal = ConvertInteger(Settings("PortalId"))
        strAdminEmail = CType(Settings("AdminEmail"), String)
        strPayPalReceiverEmail = CType(Settings("PayPalBusinessEmail"), String) 'use to check if users pay to the right person
        strPayPalMsgSuccess = CType(Settings("PayPalMsgSuccess"), String)
        strPayPalMsgError = CType(Settings("PayPalMsgError"), String)
        strPostMode = CType(Settings("PayPalOperationMode"), String).ToLower()
        ShowIPNError = ConvertBoolean(Settings("Setting_ShowIPNError"))
        IPNWaitTime = ConvertInteger(Settings("Setting_IPNWaitTime"))
        Me.thisPaypalIPNEnable = ConvertString(Settings("PaypalIPNEnable"))
        If Me.thisPaypalIPNEnable.ToString() <> "1" Then
            qs = "&msgcode=pp&msgcontent=" & HttpUtility.HtmlEncode(strPayPalMsgSuccess)
            Response.Redirect(jb_Utility.BuildDesktopLink(Me.thisTab, "msg", qs), False)
        End If


        thisPayPalFlatFeeAmount = ConvertDecimal(Settings("PayPalFlatFeeAmount"))
        thisPayPalExpirationDays_FeeBased = ConvertInteger(Settings("PayPalExpirationDays_FeeBased"))
        thisExpirationDays = ConvertInteger(Settings("ExpirationDays"))
        Me.thisRequireAuthorization = ConvertString(Settings("RequireAuthorization"))

    End Sub
    Public Sub SetPageControlProperties()
        If Not ConvertString(strAdminEmail) = "" Then
            hplContactAdmin.NavigateUrl = "mailto:" & strAdminEmail
        End If
    End Sub

    Public Sub RetrivePostedVariables()
        'core variables
        payment_gross = Request.Form("payment_gross")
        mc_gross = Request.Form("mc_gross")
        mc_fee = Request.Form("mc_fee")
        payment_status = Request.Form("payment_status")
        txn_id = Request.Form("txn_id")
        item_number = Request.Form("item_number")
        item_name = Request.Form("item_name")
        quantity = Request.Form("quantity")
        payer_email = Request.Form("payer_email")
        payer_id = Request.Form("payer_id")
        receiver_email = Request.Form("receiver_email")
        num_cart_items = CInt(Request.Form("num_cart_items"))

        'additional variables
        invoice = Request.Form("invoice")
        custom = Request.Form("custom")
        payment_status = Request.Form("payment_status")
        pending_reason = Request.Form("pending_reason")
        payment_date = Request.Form("payment_date")
        payment_fee = Request.Form("payment_fee")
        txn_type = Request.Form("txn_type")
        first_name = Request.Form("first_name")
        last_name = Request.Form("last_name")
        address_street = Request.Form("address_street")
        address_city = Request.Form("address_city")
        address_state = Request.Form("address_state")
        address_zip = Request.Form("address_zip")
        address_country = Request.Form("address_country")
        address_status = Request.Form("address_status")
        payer_status = Request.Form("payer_status")
        payment_type = Request.Form("payment_type")
        notify_version = Request.Form("notify_version")
        verify_sign = Request.Form("verify_sign")
        subscr_date = Request.Form("subscr_date")   'Start date or cancellation date depending on whether transaction is "subscr_signup" or "subscr_cancel"
        period1 = Request.Form("period1")           '(optional) Trial subscription interval in days, weeks, months, years (example: a 4 day interval is "period1: 4 d")
        period2 = Request.Form("period2")           '(optional) Trial subscription interval in days, weeks, months, years
        period3 = Request.Form("period3")           'Regular subscription interval in days, weeks, months, years
        amount1 = Request.Form("amount1")           '(optional) Amount of payment for trial period1
        amount2 = Request.Form("amount2")           '(optional) Amount of payment for trial period2
        amount3 = Request.Form("amount3")           'Amount of payment for regular period3
        recurring = Request.Form("recurring")       'Indicates whether regular rate recurs (1 is yes, 0 is no)
        reattempt = Request.Form("reattempt")       'Indicates whether reattempts should occur upon payment failures (1 is yes, 0 is no)
        retry_at = Request.Form("retry_at")         'Date we will retry failed subscription payment
        recur_times = Request.Form("recur_times")   'How many payment installments will occur at the regular rate
        username = Request.Form("username")         '(optional) Username generated by PayPal and given to subscriber to access the subscription
        subscr_id = Request.Form("subscr_id")       '(optional) ID generated by PayPal for the subscriber

        mc_shipping = ConvertDecimal(Request.Form("mc_shipping"))
        mc_handling = ConvertDecimal(Request.Form("mc_handling"))
        mc_tax = ConvertDecimal(Request.Form("mc_tax"))
        shipping = ConvertDecimal(Request.Form("shipping"))
        tax = ConvertDecimal(Request.Form("tax"))


    End Sub
    '2008
    Public Sub VerifyDuplicateTransaction()
        If objOrders.jb_Orders_pp_IsDuplicate(txn_id) = True Then 'This is a duplicate
            boolDuplicateTxn_ID = True
        Else
            boolDuplicateTxn_ID = False
        End If
    End Sub
    Public Sub PayPal_PriceCheck(ByVal ListingPrice As Decimal)
        Dim Amount_PayPal As Decimal
        Amount_PayPal = Me.mc_gross - Me.tax - Me.shipping
        If Amount_PayPal >= ListingPrice Then
            boolIsCorrectAmount = True
        Else
            If txn_type <> "web_accept" Then
                boolIsCorrectAmount = True
            Else
                boolIsCorrectAmount = False
            End If
        End If
    End Sub

    Private Function VerifyIPN(Optional ByVal PostMode As String = "live") As Boolean
        Dim formPostData As String
        Dim postKey As String
        For Each postKey In Request.Form
            Dim postValue As String = Request.Form(postKey)
            formPostData += String.Format("&{0}={1}", postKey, postValue)
        Next postKey

        formPostData += "&cmd=_notify-validate"
        Dim objStream As StreamWriter
        Dim PayPalServerURL As String

        Select Case LCase(PostMode) 'live, live-ssl, sandbox, sandbox-ssl, elite, elite-ssl 
            Case "live"
                PayPalServerURL = "https://www.paypal.com/cgi-bin/webscr"
                'PayPalServerURL = "https://www.paypal.com/us/cgi-bin/webscr"
            Case "sandbox"
                PayPalServerURL = "https://www.sandbox.paypal.com/cgi-bin/webscr"
                'PayPalServerURL = "https://www.sandbox.paypal.com/us/cgi-bin/webscr"
            Case "elite"
                PayPalServerURL = "https://www.eliteweaver.co.uk/cgi-bin/webscr"
            Case Else
                Response.Write("PostMode: " & PostMode & " is invalid! Legal values are live, sandbox, or elite")
        End Select

        Dim objRequest As HttpWebRequest = WebRequest.Create(PayPalServerURL)
        objRequest.Method = "POST"
        objRequest.ContentLength = formPostData.Length
        objRequest.ContentType = "application/x-www-form-urlencoded"

        objStream = New StreamWriter(objRequest.GetRequestStream())
        objStream.Write(formPostData)
        objStream.Close()

        Dim objResponse As HttpWebResponse = objRequest.GetResponse()
        Dim sr As StreamReader
        sr = New StreamReader(objResponse.GetResponseStream())
        Dim strResponse As String = sr.ReadToEnd()
        sr.Close()
        Return strResponse = "VERIFIED"

    End Function
</script>
<HTML dir="ltr">
	<HEAD>
		<title id="Title">PayPal IPN Handler</title>
		<META http-equiv="Content-Type" content="text/html; charset=windows-1252">
		<LINK id="StyleSheet" type="text/css" rel="stylesheet" runat="server"></LINK>
	</HEAD>
	<body id="Body" bottomMargin="0" leftMargin="0" topMargin="0" rightMargin="0" marginheight="0"
		marginwidth="0" runat="server">
		<form id="Form1" encType="multipart/form-data" runat="server">
			<table height="100%" cellSpacing="0" cellPadding="0" width="100%" border="0">
				<tr vAlign="top">
					<td vAlign="top" align="center" height="100%"><br>
						<br>
						<br>
						<asp:panel id="pnlConfirm" runat="server" BorderWidth="1" BorderStyle=Outset Visible="False"
							Width="60%" HorizontalAlign="Center">
							<P class="Normal" align="center"><BR>
								<asp:Label id="lblMessage" runat="server" CssClass="Normal">This Page handles the PayPal IPNs</asp:Label><BR>
								<BR>
								<BR>
								<BR>
								<IMG src="images/ico-mail.gif">&nbsp;
								<asp:HyperLink id="hplContactAdmin" runat="server" CssClass="Normal" text="Contact Admin"></asp:HyperLink>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								<IMG src="images/ico-home.gif">&nbsp;
								<asp:linkbutton id="cmdReturnHome" resourcekey="[RESX:Nav_ModuleHome].Text" runat="server" CssClass="Normal" Text="Return to Module Home."
									BorderStyle="none" CausesValidation="False">Return to Module Home</asp:linkbutton><BR>
								<BR>
							</P>
						</asp:panel><br>
						<asp:panel id="pnlIPNWait" runat="server" BorderStyle="Outset" BorderWidth="1" Width="30%" Visible="True" HorizontalAlign="Center">					
                            <br /><br /><br />
                            <p align="center">
                            <asp:Label ID="lblIPNWaitMessage" CssClass="JediCss_IPNWait" runat="server" Text="Please wait."></asp:Label>
                            <br /><br />
                             
                            <asp:Image ID="imgAnimation" ImageUrl="~/DesktopModules/PA_JobBoard/images/ajax-loader.gif" runat="server" ImageAlign="AbsMiddle" />
                            </p>
                            <br /><br /><br />
            			</asp:panel>
						<br>
					</td>
				</tr>
			</table>
		</form>
	</body>
</HTML>
