/* PLEASE ONLY RUN THIS ONCE, IT WILL ONLY WORK ONCE */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdResourceType SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdResourceTopics SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdResourceLanguage SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdResource ADD CONSTRAINT
	FK_bhdResource_bhdResourceLanguage FOREIGN KEY
	(
	languageId
	) REFERENCES dbo.bhdResourceLanguage
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdResource ADD CONSTRAINT
	FK_bhdResource_bhdResourceType FOREIGN KEY
	(
	typeId
	) REFERENCES dbo.bhdResourceType
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdResource ADD CONSTRAINT
	FK_bhdResource_bhdResourceTopics FOREIGN KEY
	(
	topicId
	) REFERENCES dbo.bhdResourceTopics
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdResource SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdResourceRating ADD CONSTRAINT
	FK_bhdResourceRating_bhdResource FOREIGN KEY
	(
	resourceId
	) REFERENCES dbo.bhdResource
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdResourceRating SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdPublisher SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdFileType SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdFile ADD CONSTRAINT
	FK_bhdFile_bhdFileType FOREIGN KEY
	(
	fileTypeId
	) REFERENCES dbo.bhdFileType
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdFile SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdResourceFile ADD CONSTRAINT
	FK_bhdResourceFile_bhdResource FOREIGN KEY
	(
	resourceId
	) REFERENCES dbo.bhdResource
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdResourceFile ADD CONSTRAINT
	FK_bhdResourceFile_bhdFile FOREIGN KEY
	(
	fileId
	) REFERENCES dbo.bhdFile
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdResourceFile SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdFeaturedResources ADD CONSTRAINT
	FK_bhdFeaturedResources_bhdResource FOREIGN KEY
	(
	resourceId
	) REFERENCES dbo.bhdResource
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdFeaturedResources SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdAuthor SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdPublishInformation ADD CONSTRAINT
	FK_bhdPublishInformation_bhdPublisher FOREIGN KEY
	(
	publisherId
	) REFERENCES dbo.bhdPublisher
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdPublishInformation ADD CONSTRAINT
	FK_bhdPublishInformation_bhdAuthor FOREIGN KEY
	(
	authorId
	) REFERENCES dbo.bhdAuthor
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdPublishInformation SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bhdResourceAuthor ADD CONSTRAINT
	FK_bhdResourceAuthor_bhdFile FOREIGN KEY
	(
	fileId
	) REFERENCES dbo.bhdFile
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdResourceAuthor ADD CONSTRAINT
	FK_bhdResourceAuthor_bhdAuthor FOREIGN KEY
	(
	authorId
	) REFERENCES dbo.bhdAuthor
	(
	id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.bhdResourceAuthor SET (LOCK_ESCALATION = TABLE)
GO
COMMIT